#!/bin/sh -ex

ADMIN_PASS=turnkey
DB_NAME=otrs
DB_USER=otrs

# start mysql
service mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create otrs --default-character-set=utf8;

cat <<EOF | debconf-set-selections
otrs2   otrs2/app-password-confirm  password turnkey
otrs2   otrs2/password-confirm  password turnkey
otrs2   otrs2/mysql/admin-pass  password
otrs2   otrs2/mysql/admin-user  string  root
otrs2   otrs2/dbconfig-install  boolean true
otrs2   otrs2/internal/reconfiguring    boolean false
otrs2   otrs2/install-error select  abort
otrs2   otrs2/database-type select  mysql
otrs2   otrs2/mysql/method  select  Unix socket
otrs2   otrs2/internal/skip-preseed boolean false
otrs2   otrs2/db/dbname string  $DB_NAME
otrs2   otrs2/upgrade-backup    boolean true
otrs2   otrs2/upgrade-error select  abort
otrs2   otrs2/dbconfig-reinstall    boolean false
otrs2   otrs2/db/app-user   string  $DB_NAME@localhost
otrs2   otrs2/dbconfig-remove   boolean true
otrs2   otrs2/passwords-do-not-match    error   
otrs2   otrs2/missing-db-package-error  select  abort
otrs2   otrs2/remote/port   string  
otrs2   otrs2/remote/host   select  localhost
otrs2   otrs2/purge boolean false
otrs2   otrs2/dbconfig-upgrade  boolean true
otrs2   otrs2/remote/newhost    string  
otrs2   otrs2/remove-error  select  abort
EOF

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes otrs2

SU="su otrs -s /bin/bash -c"
BIN=/usr/share/otrs/bin
# set admin password
$SU "LC_ALL=C.UTF-8 $BIN/otrs.Console.pl Admin::User::SetPassword root@localhost $ADMIN_PASS"

# configure permissions
$BIN/otrs.SetPermissions.pl \
    --otrs-user=otrs --otrs-group=www-data \
    --web-user=www-data --web-group=www-data \
    /usr/share/otrs

# configure spellcheck dictionary
ln -s /usr/lib/ispell/american.hash /usr/lib/ispell/english.hash

# Install missing dependancy
echo yes | cpan Mozilla::CA

# apache configuration
service apache2 start
echo "#dummy otrs apache conf file; real one: /etc/otrs/apache.conf" > /etc/apache2/conf-enabled/otrs2.conf
ln -s /etc/otrs/apache.conf /etc/apache2/sites-available/otrs2.conf
rm -rf /var/www/html/
a2dissite 000-default
a2ensite otrs2
a2enmod cgid

# cron email config
sed 's/^#MAILTO=\(.*\)$/MAILTO=\1/' /etc/otrs/cron

mkdir /run/otrs
chown otrs:nogroup /run/otrs
cp /usr/share/otrs/var/cron/otrs_daemon.dist /usr/share/otrs/var/cron/otrs_daemon
$SU "$BIN/Cron.sh start"

# stop services
service mysql stop
service apache2 stop

