#!/bin/bash -e
# regenerate otrs mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/etc/dbconfig-common/otrs2.conf
sed -i "s/dbc_dbpass=\(.*\)/dbc_dbpass=\'$PASSWORD\'/" $CONF
dbconfig-generate-include -f perl /etc/dbconfig-common/otrs2.conf /etc/otrs/database.pm

$INITHOOKS_PATH/bin/mysqlconf.py --user=otrs2 --pass="$PASSWORD"

service apache2 restart
