#!/bin/bash -e
# regenerate otrs mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/etc/otrs/database.pm
sed -i "s/our \$dbpass=\(.*\)/our \$dbpass=\'$PASSWORD\';/" $CONF

CONF=/etc/dbconfig-common/otrs2.conf
sed -i "s/dbc_dbpass=\(.*\)/dbc_dbpass=\'$PASSWORD\'/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=otrs --pass="$PASSWORD"

/etc/init.d/apache2 restart
